// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw0EmozI0IJLFgkI91O3xeIo54z5KCLNE',
    appId: '1:264911707486:web:94390039d4bd0a9d7803cf',
    messagingSenderId: '264911707486',
    projectId: 'sadakyatra-fd6de',
    authDomain: 'sadakyatra-fd6de.firebaseapp.com',
    storageBucket: 'sadakyatra-fd6de.appspot.com',
    measurementId: 'G-82MC5RWBDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOlEuEWxnNTkpjCZj5s_TPoef7swTNppc',
    appId: '1:264911707486:android:569c32c7eef41c197803cf',
    messagingSenderId: '264911707486',
    projectId: 'sadakyatra-fd6de',
    storageBucket: 'sadakyatra-fd6de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnZTg92jT3ui2cz5tNsPrNjw--Q9ZEJHw',
    appId: '1:264911707486:ios:e1ae796f8e65f41e7803cf',
    messagingSenderId: '264911707486',
    projectId: 'sadakyatra-fd6de',
    storageBucket: 'sadakyatra-fd6de.appspot.com',
    iosBundleId: 'com.example.sadakyatra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnZTg92jT3ui2cz5tNsPrNjw--Q9ZEJHw',
    appId: '1:264911707486:ios:e1ae796f8e65f41e7803cf',
    messagingSenderId: '264911707486',
    projectId: 'sadakyatra-fd6de',
    storageBucket: 'sadakyatra-fd6de.appspot.com',
    iosBundleId: 'com.example.sadakyatra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw0EmozI0IJLFgkI91O3xeIo54z5KCLNE',
    appId: '1:264911707486:web:ebb6febc2fb3d5c77803cf',
    messagingSenderId: '264911707486',
    projectId: 'sadakyatra-fd6de',
    authDomain: 'sadakyatra-fd6de.firebaseapp.com',
    storageBucket: 'sadakyatra-fd6de.appspot.com',
    measurementId: 'G-2HWCBP8CSD',
  );
}
